// examples/js-react-scss/src/pages/Index/index.jsx
import * as React from 'react';
import {BaseReact} from 'components/@shared/BaseReact';
import WithRoute from 'components/@shared/WithRoute';
import {ROUTES} from 'constant';
import logo from 'assets/img/logo.svg';
import {_} from 'utils/gettext';
import './index.scss';

@WithRoute(ROUTES.home)
export default class Index extends BaseReact {

  componentDidMount() {
    console.log('index')
  }

  render() {
    return (
      <div className='Index'>
        <img className='logo' src={logo} alt='logo' />
        <h1 className='welcome'>{_('Welcome to Dubo!')}</h1>
      </div>
    )
  }
}

// examples/ts-vue-scss/src/pages/Index/index.vue
<template>
  <div class='Index'>
    <img class='logo' :src='logo' />
    <h1 class='welcome'>Welcome to Dubo!</h1>
  </div>
</template>

<script lang='ts'>
import logo from 'assets/img/logo.svg';

export default {
  data() {
    return {
      logo,
    }
  }
}
</script>

<style lang='scss'>
  .Index {
    // width: r(100);
    .logo {
      width: 100%;
    }

    .welcome {
      font-size: 30px;
      text-align: center;
    }
  }
</style>
