// packages/templates/page/react/ts_scss/index.tsx
import * as React from 'react';
import {BaseReact} from 'components/@shared/BaseReact';
import WithRoute from 'components/@shared/WithRoute';
import {ROUTES} from 'constant';
import logo from 'assets/img/logo.svg';
import {_} from 'utils/gettext';
import './index.scss';

export interface I[pageName]Props {

}

export interface I[pageName]State {

}

@WithRoute(ROUTES.home)
export default class [pageName] extends BaseReact<I[pageName]Props, I[pageName]State> {

  componentDidMount() {
    console.log('index')
  }

  render() {
    return (
      <div className='[pageName]'>
        <img className='logo' src={logo} alt='logo' />
        <h1 className='welcome'>{_('Welcome to Dubo!')}</h1>
      </div>
    )
  }
}

// packages/templates/page/vue/ts_scss/index.vue
<template>
  <div class='[pageName]'>
    <img class='logo' :src='logo' />
    <h1 class='welcome'>Welcome to Dubo!</h1>
  </div>
</template>

<script lang='ts'>
import logo from 'assets/img/logo.svg';

export default {
  data() {
    return {
      logo,
    }
  }
}
</script>

<style lang='scss'>
  .[pageName] {
    // width: r(100);
    .logo {
      width: 100%;
    }

    .welcome {
      font-size: 30px;
      text-align: center;
    }
  }
</style>
